# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


User.create!(name:  "a User",
             email: "example@rails.com",
             age: 133
             )

99.times do |n|
  name  = Faker::Name.name
  email = "example-#{n+1}@rails.com"
  age = n+1
  User.create!(name:  name,
               email: email,
               age: age)
end

=begin
1000.times do |n|
    name = Faker::Music.name
    artist  = Faker::Name.name
  
  User.create!(name:  name,
               artist: artist)
end
=end
#=begin
musics=[{:name => 'Aladdin', :artist => 'iG'},
    	  {:name => 'The Terminator', :artist => 'wR'},
    	  {:name => 'When Harry Met Sally', :artist => 'R'},
      	  {:name => 'The Help', :artist => 'PG-13'},
      	  {:name => 'Chocolat', :artist => 'PG-13'},
      	  {:name => 'Amelie', :artist=> 'R'},
      	  {:name => '2001: A Space Odyssey', :artist => 'G'},
      	  {:name => 'The Incredibles', :artist => 'PG'},
      	  {:name => 'Raiders of the Lost Ark', :artist => 'PG'},
      	  {:name => 'Chicken Run', :artist => 'G'},
{:name => 'cash, johnny', :artist => 'Cash, Johnny'},
{:name => 'multitasking', :artist => 'multitasking'},
{:name => 'hot black silk', :artist => 'Hot Black Silk'},
{:name => 'england', :artist => 'England'},
{:name => 'i won', :artist => 'I Won'},
{:name => 'double trouble', :artist => 'Double trouble'},
{:name => 'freedom', :artist => 'Freedom'},
{:name => 'pretenders', :artist => 'Pretenders'},
{:name => 'everything', :artist => 'Everything'},
{:name => 'drawing board', :artist => 'Drawing board'},
{:name => 'coffee, god & cigarettes', :artist => 'Coffee, God & Cigarettes'},
{:name => 'womack, bobby', :artist => 'Womack, Bobby'},
{:name => 'blackberry smoke', :artist => 'Blackberry Smoke'},
{:name => 'brown, james', :artist => 'Brown, James'},
{:name => 'vargas blues band', :artist => 'Vargas Blues band'},
{:name => 'king tubby', :artist => 'King Tubby'},
{:name => 'education or indoctrination', :artist => 'Education or Indoctrination'},
{:name => 'panthersan', :artist => 'Panthersan'},
{:name => 'every minute is ok', :artist => 'Every Minute is OK'},
{:name => 'car wash', :artist => 'Car Wash'},
{:name => 'sonofwebcore', :artist => 'sonofwebcore'},
{:name => 'people are strange', :artist => 'People Are Strange'},
{:name => 'putin lights up the fires', :artist => 'Putin Lights Up the Fires'},
{:name => 'show of hands', :artist => 'Show of Hands'},
{:name => 'once more with feeling', :artist => 'Once More With Feeling'},
{:name => 'cia man', :artist => 'CIA Man'},
{:name => 'd', :artist => 'D'},
{:name => 'g', :artist => 'G'},
{:name => 'one second to midnight', :artist => 'One Second to Midnight'},
{:name => 'johnson, robert', :artist => 'Johnson, Robert'},
{:name => 'bharbor', :artist => 'bharbor'},
{:name => 'i', :artist => 'I'},
{:name => 'nosuchzone', :artist => 'nosuchzone'},
{:name => 'political world', :artist => 'Political World'},
{:name => 'bt', :artist => 'BT'},
{:name => 'russians and americans', :artist => 'Russians and Americans'},
{:name => 'bad brains', :artist => 'Bad Brains'},
{:name => 'patton, charley', :artist => 'Patton, Charley'},
{:name => 'give it away', :artist => 'Give It Away'},
{:name => 'god', :artist => 'God'},
{:name => 'zanes, dan & barbara brousal', :artist => 'Zanes, Dan & Barbara Brousal'},
{:name => 'im abendrot (from four last songs)', :artist => 'Im Abendrot (from Four Last Songs)'},
{:name => 'hey jean hey dean', :artist => 'Hey Jean Hey Dean'},
{:name => 'pet shop boys', :artist => 'Pet Shop Boys'},
{:name => 'forests', :artist => 'forests'},
{:name => 'baby i love you so', :artist => 'Baby I Love You So'},
{:name => 'enjoy yourself (it', :artist => 'Enjoy Yourself (It'},
{:name => 'got to give it up', :artist => 'Got to Give It Up'},
{:name => 'derniere danse', :artist => 'Derniere Danse'},
{:name => 'patton, mike', :artist => 'Patton, Mike'},
{:name => 'studio killers', :artist => 'Studio Killers'},
{:name => 'thoughtballoons', :artist => 'thoughtballoons'},
{:name => 'hey jack kerouac', :artist => 'Hey Jack Kerouac'},
{:name => 'grauzone', :artist => 'Grauzone'},
{:name => 'altered images', :artist => 'Altered Images'},
{:name => 'english rose', :artist => 'English Rose'},
{:name => 'tower of power', :artist => 'Tower of Power'},
{:name => 'alexito', :artist => 'alexito'},
{:name => 'do the robot', :artist => 'Do the Robot'},
{:name => 'prigent, denez & lisa gerrard', :artist => 'Prigent, Denez & Lisa Gerrard'},
{:name => 'high by the beach', :artist => 'High by the Beach'},
{:name => '1980s 12 " singles', :artist => '1980s 12 " Singles'},
{:name => 'metro', :artist => 'Metro'},
{:name => 'vuylsteke, michel', :artist => 'Vuylsteke, Michel'},
{:name => 'alliteration', :artist => 'alliteration'},
{:name => 'southpaw jones', :artist => 'Southpaw Jones'},
{:name => 'rhino skin', :artist => 'Rhino Skin'},
{:name => 'back in black', :artist => 'Back in Black'},
{:name => 'vinton, bobby', :artist => 'Vinton, Bobby'},
{:name => 'purcell, henry (performed by klaus nomi)', :artist => 'Purcell, Henry (performed by Klaus Nomi)'},
{:name => 'strange and surreal', :artist => 'strange and surreal'},
{:name => 'scarletsohywel', :artist => 'ScarletsOHywel'},
{:name => 'mansfield, keith', :artist => 'Mansfield, Keith'},
{:name => 'hammill, peter', :artist => 'Hammill, Peter'},
{:name => 'if you', :artist => 'If You'},
{:name => 'rough lover', :artist => 'Rough Lover'},
{:name => 'reminisce (part ii)', :artist => 'Reminisce (Part II)'},
{:name => 'rucker, ursula', :artist => 'Rucker, Ursula'},
{:name => 'i could eat crawfish every day', :artist => 'I Could Eat Crawfish Every Day'},
{:name => 'ellis-bextor, sophie', :artist => 'Ellis-Bextor, Sophie'},
{:name => 'springsteen, bruce', :artist => 'Springsteen, Bruce'},
{:name => 'chris7572', :artist => 'Chris7572'},
{:name => 'i can add', :artist => 'I Can Add'},
{:name => 'simone, nina', :artist => 'Simone, Nina'},
{:name => 'ether song', :artist => 'Ether Song'},
{:name => 'dirty deeds done dirt cheap', :artist => 'Dirty Deeds Done Dirt Cheap'},
{:name => 'kirby, leyland', :artist => 'Kirby, Leyland'},
{:name => 'paradise by the dashboard light', :artist => 'Paradise By the Dashboard Light'},
{:name => 'richie, lionel', :artist => 'Richie, Lionel'},
{:name => 'oxygène', :artist => 'Oxygène'},
{:name => 'perfect way', :artist => 'Perfect Way'},
{:name => 'i salute you christopher (ode to christopher hitchens)', :artist => 'I Salute You Christopher (Ode to Christopher Hitchens)'},
{:name => 'dreams of santa anna (extended club mix)', :artist => 'Dreams of Santa Anna (Extended Club Mix)'},
{:name => 'anti-flag', :artist => 'Anti-Flag'},
{:name => 'ukrainians', :artist => 'Ukrainians'},
{:name => 'krs-one', :artist => 'KRS-One'},
{:name => 'ill wind', :artist => 'Ill Wind'},
{:name => 'wailer, bunny', :artist => 'Wailer, Bunny'},
{:name => 'i don', :artist => 'I Don'},
{:name => 'hedonism', :artist => 'hedonism'},
{:name => 'al naafiysh (the soul)', :artist => 'Al Naafiysh (The Soul)'},
{:name => 'hand in hand', :artist => 'Hand in hand'},
{:name => 'bullfrog blues', :artist => 'Bullfrog Blues'},
{:name => 'even flow', :artist => 'Even Flow'},
{:name => 'james, danny', :artist => 'James, Danny'},
{:name => 'glass, philip', :artist => 'Glass, Philip'},
{:name => 'get rhythm', :artist => 'Get Rhythm'},
{:name => 'french rock ', :artist => 'French Rock '},
{:name => 'williams, charles and his orchestra', :artist => 'Williams, Charles and his Orchestra'},
{:name => 'clarke, john cooper', :artist => 'Clarke, John Cooper'},
{:name => 'gallagher, rory', :artist => 'Gallagher, Rory'},
{:name => 'careful with that axe, eugene (live)', :artist => 'Careful With That Axe, Eugene (live)'},
{:name => '10,000 maniacs', :artist => '10,000 Maniacs'},
{:name => 'i walked away', :artist => 'I Walked Away'},
{:name => 'lekman, jens', :artist => 'Lekman, Jens'},
{:name => 'house of jansch', :artist => 'House of Jansch'},
{:name => 'flanders and swann', :artist => 'Flanders and Swann'},
{:name => 'stevenjameshyde', :artist => 'stevenjameshyde'},
{:name => 'infernal gallop', :artist => 'Infernal Gallop'},
{:name => 'dear mr. murdoch', :artist => 'Dear Mr. Murdoch'},
{:name => 'accidental racist', :artist => 'Accidental Racist'},
{:name => 'sidecarshiv', :artist => 'SidecarShiv'},
{:name => 'music industry', :artist => 'music industry'},
{:name => 'dime in two dozen', :artist => 'Dime in two dozen'},
{:name => 'ball of confusion (that', :artist => 'Ball of Confusion (That'},
{:name => 'jeremy mortimer', :artist => 'Jeremy Mortimer'},
{:name => 'gortoz a ran', :artist => 'Gortoz a Ran'},
{:name => 'traffic experiment', :artist => 'Traffic Experiment'},
{:name => 'suzi', :artist => 'Suzi'},
{:name => 'great british mistake', :artist => 'Great British Mistake'},
{:name => 'punk tv', :artist => 'Punk TV'},
{:name => 'psychic tv', :artist => 'Psychic TV'},
{:name => 'puddynaggs', :artist => 'Puddynaggs'},
{:name => 'hey sexy', :artist => 'Hey Sexy'},
{:name => 'dylan, bob', :artist => 'Dylan, Bob'},
{:name => 'gone to america', :artist => 'Gone to America'},
{:name => 'electric wizard', :artist => 'Electric Wizard'},
{:name => 'lindenberg, udo', :artist => 'Lindenberg, Udo'},
{:name => 'guede nibo', :artist => 'Guede Nibo'},
{:name => 'discomonster', :artist => 'DiscoMonster'},
{:name => 'gillan, ian', :artist => 'Gillan, Ian'},
{:name => 'ain', :artist => 'Ain'},
{:name => 'rapunzel', :artist => 'Rapunzel'},
{:name => 'ohio players', :artist => 'Ohio Players'},
{:name => 'earth, soil and dirt', :artist => 'earth, soil and dirt'},
{:name => 'girl about town', :artist => 'Girl About Town'},
{:name => 'slovenly', :artist => 'Slovenly'},
{:name => 'grandstand', :artist => 'Grandstand'},
{:name => 'oasis', :artist => 'Oasis'},
{:name => 'startling songs', :artist => 'startling songs'},
{:name => 'government center', :artist => 'Government Center'},
{:name => 'songs about love songs', :artist => 'songs about love songs'},
{:name => 'fog on the tyne', :artist => 'Fog on the Tyne'},
{:name => 'painting by numbers', :artist => 'Painting By Numbers'},
{:name => 'this is serious mum', :artist => 'This Is Serious Mum'},
{:name => 'id', :artist => 'Id'},
{:name => 'pairubu', :artist => 'Pairubu'},
{:name => 'hotelnorth', :artist => 'hotelnorth'},
{:name => 'hello there', :artist => 'Hello There'},
{:name => 'bowie, david', :artist => 'Bowie, David'},
{:name => 'five-leaf clover', :artist => 'Five-leaf clover'},
{:name => 'expensive shit', :artist => 'Expensive Shit'},
{:name => 'garganta con arena', :artist => 'Garganta Con Arena'},
{:name => 'accountancy shanty', :artist => 'Accountancy Shanty'},
{:name => 'irony', :artist => 'irony'},
{:name => 'hill, benny', :artist => 'Hill, Benny'},
{:name => 'anarchy in the uk', :artist => 'Anarchy in the UK'},
{:name => 'ring them bells', :artist => 'Ring Them Bells'},
{:name => 'callmehorse', :artist => 'callmehorse'},
{:name => 'brightman, sarah', :artist => 'Brightman, Sarah'},
{:name => 'blegvad, peter', :artist => 'Blegvad, Peter'},
{:name => 'steeleye span', :artist => 'Steeleye Span'},
{:name => 'in the nursery', :artist => 'In the Nursery'},
{:name => 'turin brakes', :artist => 'Turin Brakes'},
{:name => 'dutronc, jacques', :artist => 'Dutronc, Jacques'},
{:name => 'good charlotte', :artist => 'Good Charlotte'},
{:name => 'ravi', :artist => 'Ravi'},
{:name => 'quicksilver messengerservice', :artist => 'Quicksilver MessengerService'},
{:name => 'a complete history of the soviet union through the eyes of a humble worker, arranged to the melody of tetris', :artist => 'A Complete History of the Soviet Union Through the Eyes of a Humble Worker, Arranged to the Melody of Tetris'},
{:name => 'bonzo dog doo-dah band', :artist => 'Bonzo Dog Doo-Dah Band'},
{:name => 'treefrogdemon', :artist => 'treefrogdemon'},
{:name => 'ngoo', :artist => 'ngoo'},
{:name => 'fashion parade', :artist => 'Fashion Parade'},
{:name => 'a hard rain', :artist => 'A Hard Rain'},
{:name => 'angelitos negros', :artist => 'Angelitos Negros'},
{:name => 'incredible string band', :artist => 'Incredible String Band'},
{:name => 'uneasy listening', :artist => 'uneasy listening'},
{:name => 'tributes', :artist => 'tributes'},
{:name => 'r.e.m.', :artist => 'R.E.M.'},
{:name => 'have more time', :artist => 'Have More Time'},
{:name => 'boys don', :artist => 'Boys Don'},
{:name => 'jackson, joe', :artist => 'Jackson, Joe'},
{:name => 'homegrown tomatoes', :artist => 'Homegrown Tomatoes'},
{:name => 'captain hook', :artist => 'Captain Hook'},
{:name => 'frogprincess', :artist => 'frogprincess'},
{:name => '7 11 roses', :artist => '7 11 Roses'},
{:name => 'misterbadexample', :artist => 'misterbadexample'},
{:name => 'flight of the conchords', :artist => 'Flight of the Conchords'},
{:name => 'handsome family', :artist => 'Handsome Family'},
{:name => 'mogdog', :artist => 'Mogdog'},
{:name => 'rock ', :artist => 'Rock '},
{:name => 'damned', :artist => 'Damned'},
{:name => 'i will go with my father a-ploughing', :artist => 'I Will Go With My Father A-Ploughing'},
{:name => 'williamson, john', :artist => 'Williamson, John'},
{:name => 'doors', :artist => 'Doors'},
{:name => 'helplessly hoping', :artist => 'Helplessly Hoping'},
{:name => 'purple sky', :artist => 'Purple Sky'},
{:name => 'radiohead', :artist => 'Radiohead'},
{:name => 'i want to know what love is', :artist => 'I Want to Know What Love Is'},
{:name => 'dusty springfield', :artist => 'Dusty Springfield'},
{:name => 'weaves', :artist => 'Weaves'},
{:name => 'tatankayotanka', :artist => 'TatankaYotanka'},
{:name => 'funeralopolis', :artist => 'Funeralopolis'},
{:name => 'ludux22', :artist => 'LuDux22'},
{:name => 'indila', :artist => 'Indila'},
{:name => 'hidden tracks', :artist => 'hidden tracks'},
{:name => 'nash, johnny', :artist => 'Nash, Johnny'},
{:name => 'holiday, billie', :artist => 'Holiday, Billie'},
{:name => 'cat empire', :artist => 'Cat Empire'},
{:name => 'kraftwerk', :artist => 'Kraftwerk'},
{:name => 'death', :artist => 'Death'},
{:name => 'horror movie', :artist => 'Horror Movie'},
{:name => 'skin', :artist => 'Skin'},
{:name => 'bill evans trio', :artist => 'Bill Evans Trio'},
{:name => 'intervention', :artist => 'Intervention'},
{:name => 'dressed in black', :artist => 'Dressed in Black'},
{:name => 'rihanna', :artist => 'Rihanna'},
{:name => 'december, 1963 (oh, what a night)', :artist => 'December, 1963 (Oh, What a Night)'},
{:name => 'tiny tim', :artist => 'Tiny Tim'},
{:name => 'wiliams, lucinda', :artist => 'Wiliams, Lucinda'},
{:name => 'basque dub foundation', :artist => 'Basque Dub Foundation'},
{:name => 'gilberto, astrud', :artist => 'Gilberto, Astrud'},
{:name => 'hot chocolate', :artist => 'Hot Chocolate'},
{:name => 'toffeeboy', :artist => 'ToffeeBoy'},
{:name => 'oneness with the forest', :artist => 'Oneness With the Forest'},
{:name => 'unity', :artist => 'unity'},
{:name => 'resurrection', :artist => 'Resurrection'},
{:name => 'iantte', :artist => 'IanTTE'},
{:name => 'happyclapper', :artist => 'happyclapper'},
{:name => 'everything but the girl', :artist => 'Everything But the Girl'},
{:name => 'englishoutlaw', :artist => 'EnglishOutlaw'},
{:name => 'gilmore, thea', :artist => 'Gilmore, Thea'},
{:name => 'freak off', :artist => 'Freak Off'},
{:name => 'coincidence', :artist => 'coincidence'},
{:name => 'a stitch in time', :artist => 'A Stitch in Time'},
{:name => 'france', :artist => 'France'},
{:name => 'cardiacs', :artist => 'Cardiacs'},
{:name => 'bitten bullet', :artist => 'Bitten bullet'},
{:name => 'blondie', :artist => 'Blondie'},
{:name => 'colourbox', :artist => 'Colourbox'},
{:name => 'carolebristol', :artist => 'CaroleBristol'},
{:name => 'they might be giants', :artist => 'They Might Be Giants'},
{:name => 'foolin', :artist => 'Foolin'},
{:name => 'kolf', :artist => 'kolf'},
{:name => 'ub40', :artist => 'UB40'},
{:name => 'ice cold', :artist => 'Ice cold'},
{:name => 'florian7', :artist => 'florian7'},
{:name => 'kimartian', :artist => 'Kimartian'},
{:name => 'sacré fran?ais', :artist => 'Sacré Fran?ais'},
{:name => 'bad decisions', :artist => 'bad decisions'},
{:name => 'painting box', :artist => 'Painting Box'},
{:name => 'jam', :artist => 'Jam'},
{:name => 'let', :artist => 'Let'},
{:name => 'by this river', :artist => 'By This River'},
{:name => 'led zeppelin', :artist => 'Led Zeppelin'},
{:name => 'franklin, aretha', :artist => 'Franklin, Aretha'},
{:name => 'amaotayku avelino sinani (el buho remix)', :artist => 'Amaotayku Avelino Sinani (El Buho Remix)'},
{:name => 'ballad of tindersticks', :artist => 'Ballad of Tindersticks'},
{:name => 'pearl jam', :artist => 'Pearl Jam'},
{:name => '50,000 miles beneath my brain', :artist => '50,000 Miles Beneath My Brain'},
{:name => 'carpgate', :artist => 'Carpgate'},
{:name => 'rene and georgette magritte with their dog after the war', :artist => 'Rene and Georgette Magritte With Their Dog After the War'},
{:name => 'glitter, gary', :artist => 'Glitter, Gary'},
{:name => 'a stream with bright fish', :artist => 'A Stream With Bright Fish'},
{:name => 'english beat', :artist => 'English Beat'},
{:name => 'thomas hope', :artist => 'Thomas Hope'},
{:name => 'davis, betty', :artist => 'Davis, Betty'},
{:name => 'i hate rock ', :artist => 'I Hate Rock '},
{:name => 'pi', :artist => 'Pi'},
{:name => 'jankowski, horst', :artist => 'Jankowski, Horst'},
{:name => 'welcome', :artist => 'welcome'},
{:name => 'heroin', :artist => 'Heroin'},
{:name => 'el cigala, diego', :artist => 'El Cigala, Diego'},
{:name => 'hisaishi, joe', :artist => 'Hisaishi, Joe'},
{:name => 'chaos', :artist => 'chaos'},
{:name => 'wink, josh', :artist => 'Wink, Josh'},
{:name => 'wyngatecarpenter', :artist => 'wyngatecarpenter'},
{:name => 'anniehawk', :artist => 'AnnieHawk'},
{:name => 'crustation', :artist => 'Crustation'},
{:name => 'public image ltd.', :artist => 'Public Image Ltd.'},
{:name => 'maki', :artist => 'Maki'},
{:name => 'alabama 3', :artist => 'Alabama 3'},
{:name => 'flight of earls', :artist => 'Flight of Earls'},
{:name => 'childhood memoires', :artist => 'Childhood memoires'},
{:name => 'edge of a cliff', :artist => 'Edge of a Cliff'},
{:name => 'brother d with collective effort', :artist => 'Brother D with Collective Effort'},
{:name => 'spann, otis', :artist => 'Spann, Otis'},
{:name => 'news, reporting & media', :artist => 'news, reporting & media'},
{:name => 'monty python', :artist => 'Monty Python'},
{:name => 'sb', :artist => 'SB'},
{:name => 'baby britain', :artist => 'Baby Britain'},
{:name => 'mohawk and the rednecks', :artist => 'Mohawk and the Rednecks'},
{:name => 'rapture', :artist => 'Rapture'},
{:name => 'chuncho', :artist => 'Chuncho'},
{:name => 'good morning britain', :artist => 'Good Morning Britain'},
{:name => 'warriors', :artist => 'Warriors'},
{:name => 'private life', :artist => 'Private Life'},
{:name => 'fish', :artist => 'Fish'},
{:name => 'life knowledge', :artist => 'Life knowledge'},
{:name => 'love, helen', :artist => 'Love, Helen'},
{:name => 'blind willie mctell', :artist => 'Blind Willie McTell'},
{:name => 'cure', :artist => 'Cure'},
{:name => 'careful with that axe, eugene', :artist => 'Careful With That Axe, Eugene'},
{:name => 'harvey, pj', :artist => 'Harvey, PJ'},
{:name => 'grateful dead', :artist => 'Grateful Dead'},
{:name => 'knopfler, mark', :artist => 'Knopfler, Mark'},
{:name => 'flatfrog', :artist => 'Flatfrog'},
{:name => 'shook, sarah & the disarmers', :artist => 'Shook, Sarah & the Disarmers'},
{:name => 'purple', :artist => 'purple'},
{:name => 'george, lowell', :artist => 'George, Lowell'},
{:name => 'bradley, charles', :artist => 'Bradley, Charles'},
{:name => 'flow, my tears', :artist => 'Flow, My Tears'},
{:name => 'impulse reaction', :artist => 'Impulse reaction'},
{:name => 'u2', :artist => 'U2'},
{:name => 'severin', :artist => 'severin'},
{:name => 'bj?rk', :artist => 'Bj?rk'},
{:name => 'herring song', :artist => 'Herring Song'},
{:name => 'rough and smooth', :artist => 'rough and smooth'},
{:name => 'frazier chorus', :artist => 'Frazier Chorus'},
{:name => 'four seasons', :artist => 'Four Seasons'},
{:name => 'modern lovers', :artist => 'Modern Lovers'},
{:name => 'bungeebill', :artist => 'BungeeBill'},
{:name => 'final solution', :artist => 'Final Solution'},
{:name => 'andrea chapman', :artist => 'Andrea Chapman'},
{:name => 'racing in the street', :artist => 'Racing in the Street'},
{:name => 'on the improve', :artist => 'On the Improve'},
{:name => 'stevenflanagan', :artist => 'StevenFlanagan'},
{:name => 'wolfe tones', :artist => 'Wolfe Tones'},
{:name => 'hammond, beres', :artist => 'Hammond, Beres'},
{:name => 'rocket science', :artist => 'Rocket science'},
{:name => 'amylee', :artist => 'amylee'},
{:name => 'dub can', :artist => 'Dub Can'},
{:name => 'vastariner???', :artist => 'vastariner???'},
{:name => 'indian ocean', :artist => 'Indian Ocean'},
{:name => 'one more', :artist => 'One More'},
{:name => 'barnes and barnes', :artist => 'Barnes and Barnes'},
{:name => 'all night long (all night)', :artist => 'All Night Long (All Night)'},
{:name => 'katzenjammer', :artist => 'Katzenjammer'},
{:name => 'clash', :artist => 'Clash'},
{:name => 'ramones', :artist => 'Ramones'},
{:name => 'power of the people', :artist => 'Power of the People'},
{:name => 'babes in the wood', :artist => 'Babes in the Wood'},
{:name => 'spiers and boden', :artist => 'Spiers and Boden'},
{:name => 'pay to cum', :artist => 'Pay to Cum'},
{:name => 'a glade somewhere', :artist => 'A Glade Somewhere'},
{:name => 'sweethomealabama', :artist => 'SweetHomeAlabama'},
{:name => 'american flag', :artist => 'American Flag'},
{:name => 'in your room', :artist => 'In Your Room'},
{:name => 'indianapolis', :artist => 'Indianapolis'},
{:name => 'fresh air', :artist => 'Fresh Air'},
{:name => 'rudie can', :artist => 'Rudie Can'},
{:name => 'tharpe, sister rosetta', :artist => 'Tharpe, Sister Rosetta'},
{:name => 'summer, donna', :artist => 'Summer, Donna'},
{:name => 'if wishes were horses (beggars would ride)', :artist => 'If Wishes Were Horses (Beggars Would Ride)'},
{:name => 'one chord wonders', :artist => 'One Chord Wonders'},
{:name => 'lowkey & faith sfx', :artist => 'Lowkey & Faith SFX'},
{:name => 'i lost my heart to a starship trooper', :artist => 'I Lost My Heart to a Starship Trooper'},
{:name => 'akazéhé par deux jeunes filles', :artist => 'Akazéhé Par Deux Jeunes Filles'},
{:name => 'inside the keeper', :artist => 'Inside the Keeper'},
{:name => 's.o.s. (state of shock)', :artist => 'S.O.S. (State of Shock)'},
{:name => '20 million things to do', :artist => '20 Million Things to Do'},
{:name => 'one moment more', :artist => 'One Moment More'},
{:name => 'incidental music', :artist => 'incidental music'},
{:name => 'mikedow', :artist => 'mikedow'},
{:name => 'prudoking', :artist => 'PrudoKing'},
{:name => 'go west', :artist => 'Go West'},
{:name => 'fatty arbuckle', :artist => 'Fatty Arbuckle'},
{:name => 'm.i.a.', :artist => 'M.I.A.'},
{:name => 'resistencia', :artist => 'Resistencia'},
{:name => 'sex pistols', :artist => 'Sex Pistols'},
{:name => 'oliver', :artist => 'Oliver'},
{:name => 'garfyabroad', :artist => 'GarfyAbroad'},
{:name => 'highway 61 revisited', :artist => 'Highway 61 Revisited'},
{:name => 'perhac, linda', :artist => 'Perhac, Linda'},
{:name => 'rogers, tim & the twin set', :artist => 'Rogers, Tim & the Twin Set'},
{:name => 'wagner, richard', :artist => 'Wagner, Richard'},
{:name => 'i guess i planted', :artist => 'I Guess I Planted'},
{:name => 'home is where the heart is', :artist => 'Home is Where the Heart Is'},
{:name => 'pattern recognition', :artist => 'Pattern Recognition'},
{:name => 'divine comedy', :artist => 'Divine Comedy'},
{:name => 'bishbosh', :artist => 'bishbosh'},
{:name => 'saints', :artist => 'Saints'},
{:name => 'funk', :artist => 'funk'},
{:name => 'cctv', :artist => 'CCTV'},
{:name => 'shivsidecar', :artist => 'ShivSidecar'},
{:name => 'fun fun fun', :artist => 'Fun Fun Fun'},
{:name => 'alison dempster', :artist => 'Alison Dempster'},
{:name => 'a longing to be absorbed for a while into a different and beautiful world', :artist => 'A Longing to Be Absorbed for a While Into a Different and Beautiful World'},
{:name => 'streetworm', :artist => 'StreetWorm'},
{:name => 'francia', :artist => 'Francia'},
{:name => 'rilo kiley', :artist => 'Rilo Kiley'},
{:name => 'falling and laughing', :artist => 'Falling and Laughing'},
{:name => 'dirty old town', :artist => 'Dirty Old Town'},
{:name => 'amon duul ii', :artist => 'Amon Duul II'},
{:name => 'funk, farley "jackmaster" & jessie saunders', :artist => 'Funk, Farley "Jackmaster" & Jessie Saunders'},
{:name => 'smith, marvin', :artist => 'Smith, Marvin'},
{:name => 'i wish i knew how it felt to be free', :artist => 'I Wish I Knew How It Felt to Be Free'},
{:name => 'stewart, al', :artist => 'Stewart, Al'},
{:name => 'imperial bedroom', :artist => 'Imperial Bedroom'},
{:name => 'sunn o))) and boris', :artist => 'Sunn O))) and Boris'},
{:name => 'flame', :artist => 'Flame'},
{:name => 'spike', :artist => 'Spike'},
{:name => 'black sabbath', :artist => 'Black Sabbath'},
{:name => 'smith, mindy', :artist => 'Smith, Mindy'},
{:name => 'paisley, brad & ll cool j', :artist => 'Paisley, Brad & LL Cool J'},
{:name => 'smiths', :artist => 'Smiths'},
{:name => 'woodentops', :artist => 'Woodentops'},
{:name => 'long ryders', :artist => 'Long Ryders'},
{:name => 'coming around again', :artist => 'Coming Around Again'},
{:name => 'fly the flag', :artist => 'Fly the Flag'},
{:name => 'marconius7', :artist => 'Marconius7'},
{:name => 'dwight yoakam', :artist => 'Dwight Yoakam'},
{:name => 'neutral milk hotel', :artist => 'Neutral Milk Hotel'},
{:name => 'disinformation', :artist => 'Disinformation'},
{:name => 'warpaint', :artist => 'Warpaint'},
{:name => 'down the dirt road blues', :artist => 'Down the Dirt Road Blues'},
{:name => 'fools rush in', :artist => 'Fools Rush In'},
{:name => 'new model army', :artist => 'New Model Army'},
{:name => 'rhinocratic oath', :artist => 'Rhinocratic Oath'},
{:name => 'heroes and villains', :artist => 'Heroes and Villains'},
{:name => 'music for funerals', :artist => 'music for funerals'},
{:name => 'flags', :artist => 'flags'},
{:name => 'pussel', :artist => 'pussel'},
{:name => 'everything crash', :artist => 'Everything Crash'},
{:name => 'congos', :artist => 'Congos'},
{:name => 'prophet has arise', :artist => 'Prophet Has Arise'},
{:name => 'brumel, antoine (performed by the early music consort of london)', :artist => 'Brumel, Antoine (performed by The Early Music Consort of London)'},
{:name => 'tindersticks', :artist => 'Tindersticks'},
{:name => 'disco/very (trevor jackson dub)', :artist => 'Disco/Very (Trevor Jackson Dub)'},
{:name => 'double trouble', :artist => 'Double Trouble'},
{:name => 'habits (stay high)', :artist => 'Habits (Stay High)'},
{:name => 'perfect storm', :artist => 'Perfect storm'},
{:name => 'galang', :artist => 'Galang'},
{:name => 'magicman', :artist => 'magicman'},
{:name => 'crime of the century', :artist => 'Crime of the century'},
{:name => 'pickin', :artist => 'Pickin'},
{:name => 'allman brothers band', :artist => 'Allman Brothers Band'},
{:name => 'pirates', :artist => 'pirates'},
{:name => 'binar0101', :artist => 'binar0101'},
{:name => 'bold sir rylas', :artist => 'Bold Sir Rylas'},
{:name => 'cool britannia', :artist => 'Cool Britannia'},
{:name => 'dirty filth mud', :artist => 'Dirty Filth Mud'},
{:name => 'call it stormy monday', :artist => 'Call It Stormy Monday'},
{:name => 'lithography', :artist => 'lithography'},
{:name => 'hello hello, i', :artist => 'Hello Hello, I'},
{:name => 'byrds', :artist => 'Byrds'},
{:name => 'huge tree in the tsukamori forest', :artist => 'Huge Tree in the Tsukamori Forest'},
{:name => 'immigrant eyes', :artist => 'Immigrant Eyes'},
{:name => 'help is coming', :artist => 'Help is Coming'},
{:name => 'robin hood', :artist => 'Robin Hood'},
{:name => 'thin lizzy', :artist => 'Thin Lizzy'},
{:name => 'candy girl', :artist => 'Candy Girl'},
{:name => 'doom', :artist => 'doom'},
{:name => 'forfallforfall', :artist => 'ForfallForFall'},
{:name => 'der tod und das m?dchen', :artist => 'Der Tod und das M?dchen'},
{:name => 'laibach', :artist => 'Laibach'},
{:name => 'en vogue', :artist => 'En Vogue'},
{:name => 'fame', :artist => 'Fame'},
{:name => 'prince', :artist => 'Prince'},
{:name => 'a matter of habit', :artist => 'A Matter of Habit'},
{:name => 'clean up woman', :artist => 'Clean Up Woman'},
{:name => 'meat loaf', :artist => 'Meat Loaf'},
{:name => 'culture', :artist => 'Culture'},
{:name => 'who', :artist => 'Who'},
{:name => 'philipphilip99', :artist => 'philipphilip99'},
{:name => 'british hustle', :artist => 'British Hustle'},
{:name => 'david perry', :artist => 'David Perry'},
{:name => 'autumn', :artist => 'Autumn'},
{:name => 'queen', :artist => 'Queen'},
{:name => 'ferry, bryan', :artist => 'Ferry, Bryan'},
{:name => 'megadom', :artist => 'megadom'},
{:name => 'drowning man', :artist => 'Drowning Man'},
{:name => 'carthy, liza', :artist => 'Carthy, Liza'},
{:name => 'chomskyochs', :artist => 'chomskyochs'},
{:name => 'favorite live versions', :artist => 'favorite live versions'},
{:name => 'from the fire to the frying pan', :artist => 'From the Fire to the Frying Pan'},
{:name => 'baloney again', :artist => 'Baloney Again'},
{:name => 'grupo vocal desandan', :artist => 'Grupo Vocal Desandan'},
{:name => 'fall', :artist => 'Fall'},
{:name => 'higher state of consciousness', :artist => 'Higher State of Consciousness'},
{:name => 'first chance', :artist => 'First chance'},
{:name => 'streets', :artist => 'Streets'},
{:name => 'dave56', :artist => 'dave56'},
{:name => 'no ambition', :artist => 'No ambition'},
{:name => 'mischief brew', :artist => 'Mischief Brew'},
{:name => 'blinded by fame', :artist => 'Blinded by fame'},
{:name => 'mathematics', :artist => 'mathematics'},
{:name => 'mike', :artist => 'mike'},
{:name => 'gomez', :artist => 'Gomez'},
{:name => 'vibrators', :artist => 'Vibrators'},
{:name => 'antisect', :artist => 'Antisect'},
{:name => 'vastariner', :artist => 'vastariner'},
{:name => 'paint me', :artist => 'Paint Me'},
{:name => 'alfhartagain', :artist => 'Alfhartagain'},
{:name => '9kairs9knots', :artist => '9kairs9knots'},
{:name => 'talking heads', :artist => 'Talking Heads'},
{:name => 'our mutual friend', :artist => 'Our Mutual Friend'},
{:name => 'monster truck', :artist => 'Monster Truck'},
{:name => 'withers, bill', :artist => 'Withers, Bill'},
{:name => 'toussaint, allen', :artist => 'Toussaint, Allen'},
{:name => 'afraidofsunlight', :artist => 'AfraidOfSunlight'},
{:name => 'nilpferd', :artist => 'nilpferd'},
{:name => 'beastie boys', :artist => 'Beastie Boys'},
{:name => 'early years', :artist => 'Early Years'},
{:name => 'sonic boom six', :artist => 'Sonic Boom Six'},
{:name => 'ring the alarm', :artist => 'Ring the Alarm'},
{:name => 'everything in its right place', :artist => 'Everything in Its Right Place'},
{:name => 'brown, bobby', :artist => 'Brown, Bobby'},
{:name => 'scritti politti', :artist => 'Scritti Politti'},
{:name => 'babybird', :artist => 'Babybird'},
{:name => 'manchester', :artist => 'Manchester'},
{:name => 'geordie', :artist => 'Geordie'},
{:name => 'equivalent exchange', :artist => 'Equivalent exchange'},
{:name => 'back to school', :artist => 'Back to School'},
{:name => 'madness', :artist => 'Madness'},
{:name => 'nilpferd', :artist => 'Nilpferd'},
{:name => 'and when i die', :artist => 'And When I Die'},
{:name => 'garland, judy', :artist => 'Garland, Judy'},
{:name => 'coinsequences', :artist => 'Coinsequences'},
{:name => 'hatti vatti ft sara brylewska', :artist => 'Hatti Vatti ft Sara Brylewska'},
{:name => 'history lesson', :artist => 'History Lesson'},
{:name => 'how we gonna make the black nation rise?', :artist => 'How We Gonna Make the Black Nation Rise?'},
{:name => 'a better son/daughter', :artist => 'A Better Son/Daughter'},
{:name => 'untergunter', :artist => 'untergunter'},
{:name => 'moore, gary & philip lynott', :artist => 'Moore, Gary & Philip Lynott'},
{:name => 'pushing up daisies', :artist => 'Pushing up daisies'},
{:name => 'schubert, franz', :artist => 'Schubert, Franz'},
{:name => 'zebda', :artist => 'Zebda'},
{:name => 'mcrae, carmen', :artist => 'McRae, Carmen'},
{:name => 'blue monday', :artist => 'Blue Monday'},
{:name => 'do the strand', :artist => 'Do the Strand'},
{:name => 'knowledge', :artist => 'knowledge'},
{:name => 'beltway bandit', :artist => 'Beltway Bandit'},
{:name => 'a bird in the hand (is worth two in the bush)', :artist => 'A Bird in the Hand (Is Worth Two in the Bush)'},
{:name => 'fibonacci sequence', :artist => 'Fibonacci Sequence'},
{:name => 'mann, aimee', :artist => 'Mann, Aimee'},
{:name => 'bllckchps', :artist => 'bllckchps'},
{:name => 'bag of mysteries', :artist => 'Bag of mysteries'},
{:name => 'silversun pickups', :artist => 'Silversun Pickups'},
{:name => 'tragedy & comedy', :artist => 'tragedy & comedy'},
{:name => 'mitra, lopamudra', :artist => 'Mitra, Lopamudra'},
{:name => 'hollywood', :artist => 'Hollywood'},
{:name => 'one people, one struggle', :artist => 'One People, One Struggle'},
{:name => 'devil', :artist => 'Devil'},
{:name => 'dream kitchen', :artist => 'Dream Kitchen'},
{:name => 'ethiopians', :artist => 'Ethiopians'},
{:name => 'matteottihologram', :artist => 'MatteottiHologram'},
{:name => 'ask the gods to pull down the sky', :artist => 'Ask the Gods to Pull Down the Sky'},
{:name => 'rockingwiththeboss', :artist => 'RockingwiththeBoss'},
{:name => 'offenbach, jacques', :artist => 'Offenbach, Jacques'},
{:name => 'come on in my kitchen', :artist => 'Come on in My Kitchen'},
{:name => 'if a no jah dub', :artist => 'If a No Jah Dub'},
{:name => 'attwilightlarks', :artist => 'attwilightlarks'},
{:name => 'french kissin', :artist => 'French Kissin'},
{:name => 'one mint julep', :artist => 'One Mint Julep'},
{:name => 'carbon monoxide', :artist => 'Carbon Monoxide'},
{:name => 'proverbes', :artist => 'Proverbes'},
{:name => 'unenforced', :artist => 'unenforced'},
{:name => 'beau dommage', :artist => 'Beau Dommage'},
{:name => 'concrete and barbed wire', :artist => 'Concrete and Barbed Wire'},
{:name => 'sainte-marie, buffy', :artist => 'Sainte-Marie, Buffy'},
{:name => 'rough god goes riding', :artist => 'Rough God Goes Riding'},
{:name => 'frankie and johnny', :artist => 'Frankie and Johnny'},
{:name => 'bangla amar sorse ilish', :artist => 'Bangla Amar Sorse Ilish'},
{:name => 'israel vibration', :artist => 'Israel Vibration'},
{:name => 'ten years after', :artist => 'Ten Years After'},
{:name => 'final impact', :artist => 'Final impact'},
{:name => 'boycott me', :artist => 'Boycott Me'},
{:name => 'delay trees', :artist => 'Delay Trees'},
{:name => 'how long has this been going on?', :artist => 'How Long Has This Been Going On?'},
{:name => 'nyro, laura', :artist => 'Nyro, Laura'},
{:name => 'fish heads', :artist => 'Fish Heads'},
{:name => 'red hot chili peppers', :artist => 'Red Hot Chili Peppers'},
{:name => 'bach, johann sebastian', :artist => 'Bach, Johann Sebastian'},
{:name => 'rainy days never stay', :artist => 'Rainy Days Never Stay'},
{:name => 'jesus and mary chain', :artist => 'Jesus and Mary Chain'},
{:name => 'gurney, ivor', :artist => 'Gurney, Ivor'},
{:name => 'keithyboy1960', :artist => 'keithyboy1960'},
{:name => 'cadogan, susan', :artist => 'Cadogan, Susan'},
{:name => 'different music', :artist => 'Different Music'},
{:name => 'prophets in the sky', :artist => 'Prophets in the Sky'},
{:name => 'cohen, leonard', :artist => 'Cohen, Leonard'},
{:name => 'in questa reggia (from turandot)', :artist => 'In Questa Reggia (from Turandot)'},
{:name => 'armstrong, louis', :artist => 'Armstrong, Louis'},
{:name => 'uniques', :artist => 'Uniques'},
{:name => 'rooms', :artist => 'rooms'},
{:name => 'good to be alive', :artist => 'Good to Be Alive'},
{:name => 'one nation under a groove', :artist => 'One Nation Under a Groove'},
{:name => 'vibronics', :artist => 'Vibronics'},
{:name => 'dynamic volume changes', :artist => 'dynamic volume changes'},
{:name => 'aretha, sing one for me', :artist => 'Aretha, Sing One For Me'},
{:name => 'pur ti miro (monteverdi)', :artist => 'Pur Ti Miro (Monteverdi)'},
{:name => 'firsts and lasts', :artist => 'firsts and lasts'},
{:name => 'children of the sea', :artist => 'Children of the Sea'},
{:name => 'flack, roberta', :artist => 'Flack, Roberta'},
{:name => 'damage control', :artist => 'Damage control'},
{:name => 'hello', :artist => 'Hello'},
{:name => 'positive songs', :artist => 'positive songs'},
{:name => 'costello, elvis', :artist => 'Costello, Elvis'},
{:name => 'parasamgate', :artist => 'parasamgate'},
{:name => 'pirates anthem', :artist => 'Pirates Anthem'},
{:name => '13 wonderful love songs', :artist => '13 Wonderful Love Songs'},
{:name => 'gases', :artist => 'gases'},
{:name => 'gold', :artist => 'Gold'},
{:name => 'clark, guy', :artist => 'Clark, Guy'},
{:name => 'domino, fats', :artist => 'Domino, Fats'},
{:name => 'cyrus, noah', :artist => 'Cyrus, Noah'},
{:name => 'stiff little fingers', :artist => 'Stiff Little Fingers'},
{:name => 'hold on', :artist => 'Hold On'},
{:name => 'prophecies', :artist => 'Prophecies'},
{:name => 'rose royce', :artist => 'Rose Royce'},
{:name => 'dean and jean', :artist => 'Dean and Jean'},
{:name => 'batyar (bigmouth strikes again)', :artist => 'Batyar (Bigmouth Strikes Again)'},
{:name => 'ravi raman', :artist => 'Ravi Raman'},
{:name => 'get happy', :artist => 'Get Happy'},
{:name => 'pirate jenny', :artist => 'Pirate Jenny'},
{:name => 'hi, we', :artist => 'Hi, We'},
{:name => 'chairmen of the board', :artist => 'Chairmen of the Board'},
{:name => 'velvet underground', :artist => 'Velvet Underground'},
{:name => 'no boundaries', :artist => 'No boundaries'},
{:name => 'balloon song', :artist => 'Balloon Song'},
{:name => 'days of the week', :artist => 'days of the week'},
{:name => 'communication breakdown', :artist => 'Communication Breakdown'},
{:name => 'waiting', :artist => 'waiting'},
{:name => 'carpio, luzmilla', :artist => 'Carpio, Luzmilla'},
{:name => 'spektor, regina', :artist => 'Spektor, Regina'},
{:name => 'fay, bill', :artist => 'Fay, Bill'},
{:name => 'che notte!', :artist => 'Che Notte!'},
{:name => 'hudswell', :artist => 'hudswell'},
{:name => 'deep in the woods', :artist => 'Deep in the Woods'},
{:name => 'growing old is getting old', :artist => 'Growing Old is Getting Old'},
{:name => 'out in the fields', :artist => 'Out in the Fields'},
{:name => 'baltic ice-breaker', :artist => 'Baltic Ice-Breaker'},
{:name => 'run straight down', :artist => 'Run Straight Down'},
{:name => 'shoegazer', :artist => 'Shoegazer'},
{:name => 'orange juice', :artist => 'Orange Juice'},
{:name => 'good fortune', :artist => 'Good Fortune'},
{:name => '9hairs9knots', :artist => '9hairs9knots'},
{:name => 'sonic youth', :artist => 'Sonic Youth'},
{:name => 'iamx', :artist => 'IAMX'},
{:name => 'children of coincidence', :artist => 'Children of Coincidence'},
{:name => 'being number one', :artist => 'Being Number One'},
{:name => 'walker, t-bone', :artist => 'Walker, T-Bone'},
{:name => 'actions speak louder than words', :artist => 'Actions Speak Louder Than Words'},
{:name => 'ohia', :artist => 'Ohia'},
{:name => 'puccini, giacomo (performed by dame joan sutherland)', :artist => 'Puccini, Giacomo (performed by Dame Joan Sutherland)'},
{:name => 'purple', :artist => 'Purple'},
{:name => 'untergunther', :artist => 'untergunther'},
{:name => 'paris, bobby', :artist => 'Paris, Bobby'},
{:name => 'die vorstellung des chaos', :artist => 'Die Vorstellung des Chaos'},
{:name => 'marcoschoir', :artist => 'marcoschoir'},
{:name => 'a different corner', :artist => 'A Different Corner'},
{:name => 'doubleplusgood', :artist => 'Doubleplusgood'},
{:name => 'boil the kettle, mother', :artist => 'Boil the Kettle, Mother'},
{:name => 'destiny street', :artist => 'Destiny Street'},
{:name => 'wood, henry', :artist => 'Wood, Henry'},
{:name => 'great blacks', :artist => 'Great Blacks'},
{:name => 'sinatra, frank', :artist => 'Sinatra, Frank'},
{:name => 'housemartins', :artist => 'Housemartins'},
{:name => 'beauty is only skin deep', :artist => 'Beauty is Only Skin Deep'},
{:name => 'funkadelic', :artist => 'Funkadelic'},
{:name => 'dreams i', :artist => 'Dreams I'},
{:name => 'germans', :artist => 'Germans'},
{:name => 'don', :artist => 'Don'},
{:name => 'big country', :artist => 'Big Country'},
{:name => 'half the world away', :artist => 'Half the World Away'},
{:name => 'suzi', :artist => 'suzi'},
{:name => 'sounds of blackness', :artist => 'Sounds of Blackness'},
{:name => 'i haven', :artist => 'I Haven'},
{:name => 'makinvaja', :artist => 'Makinvaja'},
{:name => 'forest of black', :artist => 'Forest of Black'},
{:name => 'lennon, john', :artist => 'Lennon, John'},
{:name => 'foux du fafa', :artist => 'Foux du Fafa'},
{:name => 'brooklyn funk essentials with hüsnü senlendirici', :artist => 'Brooklyn Funk Essentials with Hüsnü Senlendirici'},
{:name => 'fads and crazes', :artist => 'fads and crazes'},
{:name => 're: person i knew', :artist => 'Re: Person I Knew'},
{:name => 'robbo100', :artist => 'robbo100'},
{:name => 'die antwoord', :artist => 'Die Antwoord'},
{:name => 'rubber room', :artist => 'Rubber Room'},
{:name => 'adverts', :artist => 'Adverts'},
{:name => 'a heart disease called love', :artist => 'A Heart Disease Called Love'},
{:name => 'shaw, artie ft helen forrest', :artist => 'Shaw, Artie ft Helen Forrest'},
{:name => 'high pitched vocals', :artist => 'high pitched vocals'},
{:name => 'daydream', :artist => 'Daydream'},
{:name => 'hello', :artist => 'hello'},
{:name => 'hoshino sakura', :artist => 'Hoshino Sakura'},
{:name => 'fantasia on british sea songs', :artist => 'Fantasia on British Sea Songs'},
{:name => 'icons of filth', :artist => 'Icons of Filth'},
{:name => 'pigeons in the attic room', :artist => 'Pigeons in the Attic Room'},
{:name => 'harry, debbie', :artist => 'Harry, Debbie'},
{:name => 'dust in the wind', :artist => 'Dust in the Wind'},
{:name => 'paramhor', :artist => 'ParaMhor'},
{:name => 'pogo dancing', :artist => 'Pogo Dancing'},
{:name => 'arresting opening lines', :artist => 'arresting opening lines'},
{:name => 'resistance now', :artist => 'Resistance Now'},
{:name => 'runaway love', :artist => 'Runaway Love'},
{:name => 'ronnie talk to russia', :artist => 'Ronnie Talk to Russia'},
{:name => 'alphabet assassin', :artist => 'Alphabet Assassin'},
{:name => 'channelling pain', :artist => 'channelling pain'},
{:name => 'just the beginning', :artist => 'Just the beginning'},
{:name => 'dataportal', :artist => 'DataPortal'},
{:name => 'hurt so good', :artist => 'Hurt So Good'},
{:name => 'marley, bob', :artist => 'Marley, Bob'},
{:name => 'go down moses', :artist => 'Go Down Moses'},
{:name => 'philiphilip99', :artist => 'philiphilip99'},
{:name => 'goddess of love', :artist => 'Goddess of Love'},
{:name => 'harmonie du soir à chateauguay', :artist => 'Harmonie du Soir à Chateauguay'},
{:name => 'dead pop stars', :artist => 'Dead Pop Stars'},
{:name => 'tempest, kate', :artist => 'Tempest, Kate'},
{:name => 'ben jones', :artist => 'Ben Jones'},
{:name => 'blood swamp', :artist => 'Blood Swamp'},
{:name => 'dear mr. and mrs. record industry', :artist => 'Dear Mr. and Mrs. Record Industry'},
{:name => 'proverbs and idioms', :artist => 'proverbs and idioms'},
{:name => 'oro santo', :artist => 'Oro Santo'},
{:name => 'good one comin', :artist => 'Good One Comin'},
{:name => 'pussy riot', :artist => 'Pussy Riot'},
{:name => 'putting up resistance', :artist => 'Putting Up Resistance'},
{:name => 'previn, dory', :artist => 'Previn, Dory'},
{:name => 'primal scream', :artist => 'Primal Scream'},
{:name => 'purity', :artist => 'Purity'},
{:name => 'heligoland', :artist => 'Heligoland'},
{:name => 'contentment', :artist => 'contentment'},
{:name => 'buskerdoo', :artist => 'buskerdoo'},
{:name => 'hip priest', :artist => 'Hip Priest'},
{:name => 'high', :artist => 'high'},
{:name => 'maccoll, ewan & peggy seeger', :artist => 'MacColl, Ewan & Peggy Seeger'},
{:name => 'dearie, blossom', :artist => 'Dearie, Blossom'},
{:name => 'down in flames', :artist => 'Down in flames'},
{:name => 'a walk in the black forest', :artist => 'A Walk in the Black Forest'},
{:name => 'bakudan kowai (scary bomb)', :artist => 'Bakudan Kowai (Scary Bomb)'},
{:name => 'road to nowhere', :artist => 'Road to Nowhere'},
{:name => 'get up off your knees', :artist => 'Get Up Off Your Knees'},
{:name => 'scott, jill', :artist => 'Scott, Jill'},
{:name => 'records', :artist => 'Records'},
{:name => 'american oxygen', :artist => 'American Oxygen'},
{:name => 'vanwolf2', :artist => 'vanwolf2'},
{:name => 'pigbag', :artist => 'Pigbag'},
{:name => 'lv ft dandelion', :artist => 'LV ft Dandelion'},
{:name => 'strauss, richard (performed by jessye norman)', :artist => 'Strauss, Richard (performed by Jessye Norman)'},
{:name => 'beck, jeff', :artist => 'Beck, Jeff'},
{:name => 'unclben', :artist => 'Unclben'},
{:name => 'petty, tom & the heartbreakers', :artist => 'Petty, Tom & the Heartbreakers'},
{:name => 'cheating', :artist => 'cheating'},
{:name => 'flip, flop and fly', :artist => 'Flip, Flop and Fly'},
{:name => 'refugee children', :artist => 'Refugee Children'},
{:name => 'chelsea max', :artist => 'chelsea max'},
{:name => 'infatuation', :artist => 'Infatuation'},
{:name => 'klaatu', :artist => 'Klaatu'},
{:name => 'zevon, warren', :artist => 'Zevon, Warren'},
{:name => 'room at the top', :artist => 'Room at the Top'},
{:name => 'senser', :artist => 'Senser'},
{:name => 'minelli, liza', :artist => 'Minelli, Liza'},
{:name => 'how the love gets in', :artist => 'How the Love Gets In'},
{:name => 'waits, tom', :artist => 'Waits, Tom'},
{:name => 'rusholme ruffians', :artist => 'Rusholme Ruffians'},
{:name => 'dowland, john', :artist => 'Dowland, John'},
{:name => 'sseeeglle', :artist => 'sseeeglle'},
{:name => 'clovers', :artist => 'Clovers'},
{:name => 'leaveitallbehind', :artist => 'Leaveitallbehind'},
{:name => 'evening prayer', :artist => 'Evening Prayer'},
{:name => 'gunter kallmann choir', :artist => 'Gunter Kallmann Choir'},
{:name => 'a bar in amsterdam', :artist => 'A Bar in Amsterdam'},
{:name => 'sonic boom 6', :artist => 'Sonic Boom 6'},
{:name => 'get up offa that thing', :artist => 'Get Up Offa That Thing'},
{:name => 'fat freddy', :artist => 'Fat Freddy'},
{:name => 'rundgren, todd', :artist => 'Rundgren, Todd'},
{:name => 'smith, elliott', :artist => 'Smith, Elliott'},
{:name => 'shangri-las', :artist => 'Shangri-Las'},
{:name => 'gimmix! (play loud)', :artist => 'Gimmix! (Play Loud)'},
{:name => 'el secuestro del dub', :artist => 'El Secuestro del Dub'},
{:name => 'cassette 2012', :artist => 'Cassette 2012'},
{:name => 'fluke', :artist => 'Fluke'},
{:name => 'barbryn', :artist => 'barbryn'},
{:name => 'ben wood', :artist => 'Ben Wood'},
{:name => 'into the mystic', :artist => 'Into the Mystic'},
{:name => 'in the middle of the night', :artist => 'In the Middle of the Night'},
{:name => 'skyhooks', :artist => 'Skyhooks'},
{:name => 'paint her face', :artist => 'Paint Her Face'},
{:name => 'collins, dave and ansell', :artist => 'Collins, Dave and Ansell'},
{:name => 'girsa', :artist => 'GIRSA'},
{:name => 'id5515151', :artist => 'ID5515151'},
{:name => 'black box recorder', :artist => 'Black Box Recorder'},
{:name => 'staple singers', :artist => 'Staple Singers'},
{:name => 'fuel', :artist => 'Fuel'},
{:name => 'grinderswitch', :artist => 'Grinderswitch'},
{:name => 'forest', :artist => 'Forest'},
{:name => 'parallelograms', :artist => 'Parallelograms'},
{:name => 'overseer', :artist => 'Overseer'},
{:name => 'portrait of a man', :artist => 'Portrait of a Man'},
{:name => 'van der graaf generator', :artist => 'Van Der Graaf Generator'},
{:name => 'melanie', :artist => 'Melanie'},
{:name => 'gimme some truth', :artist => 'Gimme Some Truth'},
{:name => 'id7033168', :artist => 'ID7033168'},
{:name => 'earthling', :artist => 'Earthling'},
{:name => 'muldrow, georgia anne', :artist => 'Muldrow, Georgia Anne'},
{:name => 'history', :artist => 'History'},
{:name => 'istanbul twilight', :artist => 'Istanbul Twilight'},
{:name => 'jacquescustard', :artist => 'JacquesCustard'},
{:name => 'orlando, tony', :artist => 'Orlando, Tony'},
{:name => 'sweet honey in the rock', :artist => 'Sweet Honey in the Rock'},
{:name => 'havens, richie', :artist => 'Havens, Richie'},
{:name => 'double dutch', :artist => 'Double Dutch'},
{:name => 'thebeast', :artist => 'TheBeast'},
{:name => 'ohm sweet ohm', :artist => 'Ohm Sweet Ohm'},
{:name => 'and breeding', :artist => 'And Breeding'},
{:name => 'darceysdad', :artist => 'DarceysDad'},
{:name => 'cale, john', :artist => 'Cale, John'},
{:name => 'i-roy', :artist => 'I-Roy'},
{:name => 'aoxomoxoa93', :artist => 'AoxomoxoA93'},
{:name => 'dance of knights', :artist => 'Dance of Knights'},
{:name => 'britain', :artist => 'Britain'},
{:name => 'uncleben', :artist => 'Uncleben'},
{:name => '78 stone wobble', :artist => '78 Stone Wobble'},
{:name => 'james, dick', :artist => 'James, Dick'},
{:name => 'buck and the preacher', :artist => 'Buck and the Preacher'},
{:name => 'king, bb', :artist => 'King, BB'},
{:name => 'one more mile to go', :artist => 'One More Mile to Go'},
{:name => 'bailey, roy', :artist => 'Bailey, Roy'},
{:name => 'aztec camera', :artist => 'Aztec Camera'},
{:name => 'r.e.s.', :artist => 'R.E.S.'},
{:name => 'crowded house', :artist => 'Crowded House'},
{:name => 'fugs', :artist => 'Fugs'},
{:name => 'cat power', :artist => 'Cat Power'},
{:name => 'ac/dc', :artist => 'AC/DC'},
{:name => 'specials', :artist => 'Specials'},
{:name => 'fine young cannibals', :artist => 'Fine Young Cannibals'},
{:name => 'beasts of beauty', :artist => 'Beasts of beauty'},
{:name => 'neu!', :artist => 'Neu!'},
{:name => 'cake', :artist => 'Cake'},
{:name => 'come to me', :artist => 'Come to Me'},
{:name => 'gloria from missa et ecce terra motus', :artist => 'Gloria from Missa et Ecce Terra Motus'},
{:name => 'hi ho silver lining', :artist => 'Hi Ho Silver Lining'},
{:name => 'new order', :artist => 'New Order'},
{:name => 'foreigner', :artist => 'Foreigner'},
{:name => 'dimitri from paris', :artist => 'Dimitri From Paris'},
{:name => 'thesubhuman', :artist => 'Thesubhuman'},
{:name => 'rodgers, jimmie', :artist => 'Rodgers, Jimmie'},
{:name => 'deep purple', :artist => 'Deep Purple'},
{:name => 'eisbaer', :artist => 'Eisbaer'},
{:name => 'one', :artist => 'one'},
{:name => 'steer, serafina', :artist => 'Steer, Serafina'},
{:name => 'sunnydoomsdaynight', :artist => 'sunnydoomsdaynight'},
{:name => 'prelude and fugue no 1 in c major', :artist => 'Prelude and Fugue No 1 in C Major'},
{:name => 'fish', :artist => 'fish'},
{:name => 'taylor, roger', :artist => 'Taylor, Roger'},
{:name => 'yak3', :artist => 'Yak3'},
{:name => 'friday night at the drive-in bingo', :artist => 'Friday Night at the Drive-in Bingo'},
{:name => 'montecerdi, claudio (performed by elin manahan thomas & robin blaze', :artist => 'Montecerdi, Claudio (performed by Elin Manahan Thomas & Robin Blaze'},
{:name => 'kuti, fela', :artist => 'Kuti, Fela'},
{:name => 'violet vivid', :artist => 'Violet Vivid'},
{:name => 'going home', :artist => 'Going Home'},
{:name => 'facts of life', :artist => 'Facts of Life'},
{:name => 'phillipson, petra jean', :artist => 'Phillipson, Petra Jean'},
{:name => 'krautrock', :artist => 'krautrock'},
{:name => 'one love', :artist => 'One Love'},
{:name => 'a plague of lighthouse keepers', :artist => 'A Plague of Lighthouse Keepers'},
{:name => 'almond, marc', :artist => 'Almond, Marc'},
{:name => 'every bloody emperor', :artist => 'Every Bloody Emperor'},
{:name => 'los de abajo', :artist => 'Los de Abajo'},
{:name => 'del rey, lana', :artist => 'Del Rey, Lana'},
{:name => 'calling occupants of interplanetary craft', :artist => 'Calling Occupants of Interplanetary Craft'},
{:name => 'misty', :artist => 'Misty'},
{:name => 'girls and boys', :artist => 'Girls and Boys'},
{:name => 'moddi', :artist => 'Moddi'},
{:name => 'funny how love is', :artist => 'Funny How Love Is'},
{:name => 'hickox, tom', :artist => 'Hickox, Tom'},
{:name => 'gordonimmel', :artist => 'gordonimmel'},
{:name => 'drunkenpanda', :artist => 'drunkenpanda'},
{:name => 'beltwaybandit', :artist => 'BeltwayBandit'},
{:name => 'philip loveland', :artist => 'Philip Loveland'},
{:name => 'patlux', :artist => 'PatLux'},
{:name => 'bel canto', :artist => 'Bel Canto'},
{:name => 'pink floyd', :artist => 'Pink Floyd'},
{:name => 'tincanman', :artist => 'tincanman'},
{:name => 'thegreatpoochini', :artist => 'TheGreatPoochini'},
{:name => 'are ruk ja re bande (bandeh)', :artist => 'Are Ruk Ja Re Bande (Bandeh)'},
{:name => 'mclaren, malcolm', :artist => 'McLaren, Malcolm'},
{:name => 'oinklmsammy', :artist => 'OinklmSammy'},
{:name => 'purple haze', :artist => 'Purple Haze'},
{:name => 'melroy', :artist => 'MelRoy'},
{:name => 'fisherman', :artist => 'Fisherman'},
{:name => 'in the aeroplane over the sea', :artist => 'In the Aeroplane Over the Sea'},
{:name => 'indifference', :artist => 'Indifference'},
{:name => 'illegally', :artist => 'Illegally'},
{:name => 'eno, brian', :artist => 'Eno, Brian'},
{:name => 'genre-switch', :artist => 'genre-switch'},
{:name => 'trophyshy', :artist => 'trophyshy'},
{:name => 'hashim', :artist => 'Hashim'},
{:name => 'diddley, bo', :artist => 'Diddley, Bo'},
{:name => 'hawkins, screamin', :artist => 'Hawkins, Screamin'},
{:name => 'hard to handle', :artist => 'Hard to Handle'},
{:name => 'panic', :artist => 'Panic'},
{:name => 'jimi hendrix experience', :artist => 'Jimi Hendrix Experience'},
{:name => 'priests', :artist => 'Priests'},
{:name => 'cassandra', :artist => 'Cassandra'},
{:name => 'songbarlandlord', :artist => 'SongBarLandlord'},
{:name => 'bottle rockets', :artist => 'Bottle Rockets'},
{:name => 'fifty years after the fair', :artist => 'Fifty Years After the Fair'},
{:name => 'orange lemon', :artist => 'Orange Lemon'},
{:name => 'lo, tove', :artist => 'Lo, Tove'},
{:name => 'lagado', :artist => 'Lagado'},
{:name => 'russia', :artist => 'Russia'},
{:name => 'harmonies', :artist => 'harmonies'},
{:name => 'sumac, yma', :artist => 'Sumac, Yma'},
{:name => 'europe is lost', :artist => 'Europe is Lost'},
{:name => 'gratitude and thanks', :artist => 'Gratitude and Thanks'},
{:name => 'daddypig', :artist => 'DaddyPig'},
{:name => 'all men are pigs', :artist => 'All Men Are Pigs'},
{:name => 'morrison, van', :artist => 'Morrison, Van'},
{:name => 'orchestra harlow', :artist => 'Orchestra Harlow'},
{:name => 'gold, alice', :artist => 'Gold, Alice'},
{:name => 'propaganda', :artist => 'propaganda'},
{:name => 'channel of hatred', :artist => 'Channel of hatred'},
{:name => 'all ones and zeros', :artist => 'All Ones and Zeros'},
{:name => 'cluster', :artist => 'Cluster'},
{:name => 'wagoner, porter', :artist => 'Wagoner, Porter'},
{:name => 'brand new key', :artist => 'Brand New Key'},
{:name => 'hi-tension', :artist => 'Hi-Tension'},
{:name => 'i can see clearly now', :artist => 'I Can See Clearly Now'},
{:name => 'wild man fischer', :artist => 'Wild Man Fischer'},
{:name => 'as if it always happens', :artist => 'As If It Always Happens'},
{:name => 'hell, richard & the voidoids', :artist => 'Hell, Richard & the Voidoids'},
{:name => 'after we shot the grizzly', :artist => 'After We Shot The Grizzly'},
{:name => 'boogie in the mud', :artist => 'Boogie in the Mud'},
{:name => 'ernie (the fastest milkman in the west)', :artist => 'Ernie (The Fastest Milkman in the West)'},
{:name => 'no doubt', :artist => 'No Doubt'},
{:name => 'barbara and the browns', :artist => 'Barbara and the Browns'},
{:name => 'buffalo soldier', :artist => 'Buffalo Soldier'},
{:name => 'samaris', :artist => 'Samaris'},
{:name => 'northdevion', :artist => 'Northdevion'},
{:name => 'bush, kate', :artist => 'Bush, Kate'},
{:name => 'für immer', :artist => 'Für Immer'},
{:name => 'cat killed curiosity', :artist => 'Cat killed curiosity'},
{:name => 'temptations', :artist => 'Temptations'},
{:name => 'fogerty, john', :artist => 'Fogerty, John'},
{:name => 'love is...', :artist => 'love is...'},
{:name => 'fighting my way back', :artist => 'Fighting My Way Back'},
{:name => 'pere ubu', :artist => 'Pere Ubu'},
{:name => 'class act', :artist => 'Class act'},
{:name => 'painters and painting', :artist => 'Painters and Painting'},
{:name => 'birthday party', :artist => 'Birthday Party'},
{:name => 'before my time', :artist => 'Before My Time'},
{:name => 'dirty boots', :artist => 'Dirty Boots'},
{:name => 'loss', :artist => 'loss'},
{:name => 'i will', :artist => 'I Will'},
{:name => 'brown, joe', :artist => 'Brown, Joe'},
{:name => 'no direction', :artist => 'No direction'},
{:name => 'gaye, marvin', :artist => 'Gaye, Marvin'},
{:name => 'eye to eye', :artist => 'Eye to eye'},
{:name => 'marvelettes', :artist => 'Marvelettes'},
{:name => 'albahooky', :artist => 'AlBahooky'},
{:name => 'ochongodeo', :artist => 'ochongodeo'},
{:name => 'roxy music', :artist => 'Roxy Music'},
{:name => 'donovan', :artist => 'Donovan'},
{:name => 'stuck or trapped', :artist => 'stuck or trapped'},
{:name => 'archangel thunderbird', :artist => 'Archangel Thunderbird'},
{:name => 'wright, betty', :artist => 'Wright, Betty'},
{:name => 'f.u.n.k.', :artist => 'F.U.N.K.'},
{:name => 'bragg, billy & wilco', :artist => 'Bragg, Billy & Wilco'},
{:name => 'resistance', :artist => 'resistance'},
{:name => 'glass house', :artist => 'Glass house'},
{:name => 'disco compilation', :artist => 'Disco Compilation'},
{:name => 'enchanted forest', :artist => 'Enchanted Forest'},
{:name => 'funkbrother69', :artist => 'Funkbrother69'},
{:name => 'blue velvet', :artist => 'Blue Velvet'},
{:name => 'play for today', :artist => 'Play for Today'},
{:name => 'long blondes', :artist => 'Long Blondes'},
{:name => 'thelandbeyond', :artist => 'TheLandBeyond'},
{:name => 'i saw it on tv', :artist => 'I Saw It on TV'},
{:name => 'haydn, joseph', :artist => 'Haydn, Joseph'},
{:name => 'brilliant green', :artist => 'Brilliant Green'},
{:name => 'the obvious', :artist => 'the obvious'},
{:name => '(he', :artist => '(He'},
{:name => 'be my guest', :artist => 'Be My Guest'},
{:name => 'fatherchewylouie', :artist => 'FatherChewyLouie'},
{:name => 'blackcombe', :artist => 'BlackCombe'},
{:name => 'i feel love (patrick cowley remix)', :artist => 'I Feel Love (Patrick Cowley Remix)'},
{:name => 'on est chez nous', :artist => 'On Est Chez Nous'},
{:name => 'taylor, chip', :artist => 'Taylor, Chip'},
{:name => 'reefer madness', :artist => 'Reefer Madness'},
{:name => 'deanofromoz', :artist => 'deanofromoz'},
{:name => 'velvelettes', :artist => 'Velvelettes'},
{:name => 'movie and tv stars', :artist => 'movie and TV stars'},
{:name => 'rhymin', :artist => 'Rhymin'},
{:name => 'buika, concha & javier limón', :artist => 'Buika, Concha & Javier Limón'},
{:name => 'smith, patti', :artist => 'Smith, Patti'},
{:name => 'pretty pride of russia', :artist => 'Pretty Pride of Russia'},
{:name => 'a house', :artist => 'A House'},
{:name => 'zainichi funk', :artist => 'Zainichi Funk'},
{:name => 'eurythmics', :artist => 'Eurythmics'},
{:name => 'home t, cocoa tea & shabba ranks', :artist => 'Home T, Cocoa Tea & Shabba Ranks'},
{:name => 'id9598325', :artist => 'ID9598325'},
{:name => 'aislers set', :artist => 'Aislers Set'},
{:name => 'got the time', :artist => 'Got the Time'},
{:name => 'sweetness', :artist => 'sweetness'},
{:name => 'lindisfarne', :artist => 'Lindisfarne'},
{:name => 'jarre, jean michel', :artist => 'Jarre, Jean Michel'},
{:name => 'hot pants', :artist => 'Hot Pants'},
{:name => 'chance', :artist => 'Chance'},
{:name => 'influenced by dub', :artist => 'influenced by dub'},
{:name => 'pig with the face of a boy', :artist => 'Pig With the Face of a Boy'},
{:name => 'the last straw', :artist => 'The last straw'},
{:name => 'snarky puppy ft malika tirolian', :artist => 'Snarky Puppy ft Malika Tirolian'},
{:name => 'accidents', :artist => 'Accidents'},
{:name => 'optimistic', :artist => 'Optimistic'},
{:name => 'bethnoir', :artist => 'Bethnoir'},
{:name => 'cooder, ry', :artist => 'Cooder, Ry'},
{:name => 'black starliner must come', :artist => 'Black Starliner Must Come'},
{:name => 'turner, big joe', :artist => 'Turner, Big Joe'},
{:name => 'in the morning when i rise', :artist => 'In the Morning When I Rise'},
{:name => 'ride of the valkyries', :artist => 'Ride of the Valkyries'},
{:name => 'simon, carly', :artist => 'Simon, Carly'},
{:name => 'jaar, nicolas', :artist => 'Jaar, Nicolas'},
{:name => 'cousin jack', :artist => 'Cousin Jack'},
{:name => 'molly hatchet', :artist => 'Molly Hatchet'},
{:name => 'budd, harold & brian eno', :artist => 'Budd, Harold & Brian Eno'},
{:name => 'beach boys', :artist => 'Beach Boys'},
{:name => 'hello i love you', :artist => 'Hello I Love You'},
{:name => 'tarquinspodd', :artist => 'TarquinSpodd'},
{:name => 'first transmission', :artist => 'First Transmission'},
{:name => 'come together', :artist => 'Come Together'},
{:name => 'prophets and prophecies', :artist => 'prophets and prophecies'},
{:name => 'can', :artist => 'Can'},
{:name => 'afictionhabit', :artist => 'AFictionHabit'},
{:name => 'people have the power', :artist => 'People Have the Power'},
{:name => 'dexys midnight runners', :artist => 'Dexys Midnight Runners'},
{:name => 'repression', :artist => 'repression'},
{:name => 'rantaghost', :artist => 'RANTaGHOST'},
{:name => 'simon, paul', :artist => 'Simon, Paul'},
{:name => 'bethnoir', :artist => 'bethnoir'},
{:name => 'rolling home', :artist => 'Rolling Home'},
{:name => 'prokofiev, sergei', :artist => 'Prokofiev, Sergei'},
{:name => 'recovery', :artist => 'recovery'},
{:name => 'michael, george', :artist => 'Michael, George'},
{:name => 'didn', :artist => 'Didn'},
{:name => 'lenya, lotte', :artist => 'Lenya, Lotte'},
{:name => 'spin doctors', :artist => 'Spin Doctors'},
{:name => 'lyntoncrosby', :artist => 'LyntonCrosby'},
{:name => 'spotthewhopper', :artist => 'SpotTheWhopper'},
{:name => 'public enemy ft paris', :artist => 'Public Enemy ft Paris'},
{:name => 'bangles', :artist => 'Bangles'},
{:name => 'dedication to the cause', :artist => 'Dedication to the cause'},
{:name => 'papa', :artist => 'Papa'},
{:name => 'feast of the mau mau', :artist => 'Feast of the Mau Mau'},
{:name => 'staton, candi', :artist => 'Staton, Candi'},
{:name => 'immigrants & refugees', :artist => 'immigrants & refugees'},
{:name => 'double barrel', :artist => 'Double Barrel'},
{:name => 'great stone', :artist => 'Great Stone'},
{:name => 'everybody hurts', :artist => 'Everybody Hurts'},
{:name => 'guilt', :artist => 'Guilt'}
  	 ] 
musics.each do |music|
  Music.create!(music)
end

#=end